const messageChats = [
    { "text": "Hello! How can I help you?", "sender": "bot" },
    { "text": "Hey! I am fine, what about you?", "sender": "user" },
    { "text": "I'm just a bot, but I'm always ready to help!", "sender": "bot" },
    { "text": "That's great! Can you tell me a joke?", "sender": "user" },
    { "text": "Sure! Why don't skeletons fight each other? Because they don't have the guts!", "sender": "bot" },
    { "text": "Haha! That's a good one.", "sender": "user" },
    { "text": "I'm glad you liked it!", "sender": "bot" },
    { "text": "So, what else can you do?", "sender": "user" },
    { "text": "I can answer questions, tell jokes, give advice, and more!", "sender": "bot" },
    { "text": "That sounds cool. Can you suggest a good movie?", "sender": "user" },
    { "text": "Sure! Have you watched 'Inception'? It's a great movie!", "sender": "bot" },
    { "text": "Oh yes! I love that movie.", "sender": "user" },
    { "text": "Nice choice! Do you want a movie recommendation based on a specific genre?", "sender": "bot" },
    { "text": "Yes, I love sci-fi movies!", "sender": "user" },
    { "text": "Then you should watch 'Interstellar'! It's an amazing sci-fi movie.", "sender": "bot" },
    { "text": "Oh, I've heard about it. I'll watch it soon!", "sender": "user" },
    { "text": "Great choice! You'll love it.", "sender": "bot" },
    { "text": "Thanks! Can you also suggest some good books?", "sender": "user" },
    { "text": "Of course! If you like thrillers, try 'The Da Vinci Code' by Dan Brown.", "sender": "bot" },
    { "text": "That sounds interesting. I'll check it out!", "sender": "user" },
    { "text": "Awesome! Let me know if you need more suggestions.", "sender": "bot" },
    { "text": "Sure! By the way, can you help me with some coding stuff?", "sender": "user" },
    { "text": "Of course! What do you need help with?", "sender": "bot" },
    { "text": "I'm learning JavaScript. Can you explain closures?", "sender": "user" },
    { "text": "Sure! A closure is a function that has access to its own scope, the scope of the outer function, and the global scope.", "sender": "bot" },
    { "text": "Can you give me an example?", "sender": "user" },
    { "text": "Definitely! Here’s an example: function outer() { let count = 0; return function inner() { count++; console.log(count); } }", "sender": "bot" },
    { "text": "Oh, I see! So 'inner' function remembers 'count' even after 'outer' has executed?", "sender": "user" },
    { "text": "Exactly! That’s the power of closures.", "sender": "bot" },
    { "text": "Nice! Thanks for explaining.", "sender": "user" },
    { "text": "You're welcome! Do you want to learn more concepts?", "sender": "bot" },
    { "text": "Yes! Can you explain promises?", "sender": "user" },
    { "text": "Sure! A promise represents a value that may be available now, or in the future, or never.", "sender": "bot" },
    { "text": "That makes sense!", "sender": "user" },
    { "text": "Glad to hear that! Keep practicing.", "sender": "bot" },
    { "text": "I will! Thanks for your help.", "sender": "user" },
    { "text": "You're always welcome!", "sender": "bot" },
    { "text": "Let's talk about something fun. What's your favorite color?", "sender": "user" },
    { "text": "I don't have favorites, but blue seems to be quite popular!", "sender": "bot" },
    { "text": "Yeah, blue is really nice.", "sender": "user" },
    { "text": "Agreed!", "sender": "bot" },
    { "text": "Can you play music?", "sender": "user" },
    { "text": "I wish I could! But I can recommend songs for you!", "sender": "bot" },
    { "text": "That would be great! Suggest a song.", "sender": "user" },
    { "text": "How about 'Blinding Lights' by The Weeknd? It's a great song!", "sender": "bot" },
    { "text": "Oh, I love that song!", "sender": "user" },
    { "text": "Glad you like it!", "sender": "bot" },
    { "text": "This has been a fun chat!", "sender": "user" },
    { "text": "I'm glad you enjoyed it!", "sender": "bot" },
    { "text": "Talk to you later!", "sender": "user" },
    { "text": "Goodbye! Have a great day!", "sender": "bot" }
  ]

  
  export default messageChats