const messageChats = [
  { text: "Hello! How can I help you?", sender: "bot", time: "08:20 AM" },
  { text: "Hey! I am fine, what about you?", sender: "user", messageStatus: "sent", time: "08:21 AM" },
  { text: "I'm just a bot, but I'm always ready to help!", sender: "bot", time: "08:22 AM" },
  { text: "That's great! Can you tell me a joke?", sender: "user", messageStatus: "delivered", time: "08:23 AM" },
  { text: "Sure! Why don't skeletons fight each other? Because they don't have the guts!", sender: "bot", time: "08:24 AM" },
  { text: "Haha! That's a good one.", sender: "user", messageStatus: "read", time: "08:25 AM" },
  { text: "I'm glad you liked it!", sender: "bot", time: "08:26 AM" },
  { text: "So, what else can you do?", sender: "user", messageStatus: "delivered", time: "08:27 AM" },
  { text: "I can answer questions, tell jokes, give advice, and more!", sender: "bot", time: "08:28 AM" },
  { text: "That sounds cool. Can you suggest a good movie?", sender: "user", messageStatus: "sent", time: "08:29 AM" },
  { text: "Sure! Have you watched 'Inception'? It's a great movie!", sender: "bot", time: "08:30 AM" },
  { text: "Oh yes! I love that movie.", sender: "user", messageStatus: "read", time: "08:31 AM" },
  { text: "Nice choice! Do you want a movie recommendation based on a specific genre?", sender: "bot", time: "08:32 AM" },
  { text: "Yes, I love sci-fi movies!", sender: "user", messageStatus: "sent", time: "08:33 AM" },
  { text: "Then you should watch 'Interstellar'! It's an amazing sci-fi movie.", sender: "bot", time: "08:34 AM" },
  { text: "Oh, I've heard about it. I'll watch it soon!", sender: "user", messageStatus: "delivered", time: "08:35 AM" },
  { text: "Great choice! You'll love it.", sender: "bot", time: "08:36 AM" },
  { text: "Thanks! Can you also suggest some good books?", sender: "user", messageStatus: "sent", time: "08:37 AM" },
  { text: "Of course! If you like thrillers, try 'The Da Vinci Code' by Dan Brown.", sender: "bot", time: "08:38 AM" },
  { text: "That sounds interesting. I'll check it out!", sender: "user", messageStatus: "read", time: "08:39 AM" },
  { text: "Awesome! Let me know if you need more suggestions.", sender: "bot", time: "08:40 AM" },
  { text: "Sure! By the way, can you help me with some coding stuff?", sender: "user", messageStatus: "delivered", time: "08:41 AM" },
  { text: "Of course! What do you need help with?", sender: "bot", time: "08:42 AM" },
  { text: "I'm learning JavaScript. Can you explain closures?", sender: "user", messageStatus: "sent", time: "08:43 AM" },
  { text: "Sure! A closure is a function that has access to its own scope, the scope of the outer function, and the global scope.", sender: "bot", time: "08:44 AM" },
  { text: "Can you give me an example?", sender: "user", messageStatus: "delivered", time: "08:45 AM" },
  { text: "Definitely! Here’s an example: function outer() { let count = 0; return function inner() { count++; console.log(count); } }", sender: "bot", time: "08:46 AM" },
  { text: "Oh, I see! So 'inner' function remembers 'count' even after 'outer' has executed?", sender: "user", messageStatus: "read", time: "08:47 AM" },
  { text: "Exactly! That’s the power of closures.", sender: "bot", time: "08:48 AM" },
  { text: "Nice! Thanks for explaining.", sender: "user", messageStatus: "sent", time: "08:49 AM" },
  { text: "You're welcome! Do you want to learn more concepts?", sender: "bot", time: "08:50 AM" },
  { text: "Yes! Can you explain promises?", sender: "user", messageStatus: "delivered", time: "08:51 AM" },
  { text: "Sure! A promise represents a value that may be available now, or in the future, or never.", sender: "bot", time: "08:52 AM" },
  { text: "That makes sense!", sender: "user", messageStatus: "read", time: "08:53 AM" },
  { text: "Glad to hear that! Keep practicing.", sender: "bot", time: "08:54 AM" },
  { text: "I will! Thanks for your help.", sender: "user", messageStatus: "sent", time: "08:55 AM" },
  { text: "You're always welcome!", sender: "bot", time: "08:56 AM" },
  { text: "Let's talk about something fun. What's your favorite color?", sender: "user", messageStatus: "delivered", time: "08:57 AM" },
  { text: "I don't have favorites, but blue seems to be quite popular!", sender: "bot", time: "08:58 AM" },
  { text: "Yeah, blue is really nice.", sender: "user", messageStatus: "sent", time: "08:59 AM" },
  { text: "Agreed!", sender: "bot", time: "09:00 AM" },
  { text: "Can you play music?", sender: "user", messageStatus: "read", time: "09:01 AM" },
  { text: "I wish I could! But I can recommend songs for you!", sender: "bot", time: "09:02 AM" },
  { text: "That would be great! Suggest a song.", sender: "user", messageStatus: "delivered", time: "09:03 AM" },
  { text: "How about 'Blinding Lights' by The Weeknd? It's a great song!", sender: "bot", time: "09:04 AM" },
  { text: "Oh, I love that song!", sender: "user", messageStatus: "sent", time: "09:05 AM" },
  { text: "Glad you like it!", sender: "bot", time: "09:06 AM" },
  { text: "This has been a fun chat!", sender: "user", messageStatus: "delivered", time: "09:07 AM" },
  { text: "I'm glad you enjoyed it!", sender: "bot", time: "09:08 AM" },
  { text: "Talk to you later!", sender: "user", messageStatus: "read", time: "09:09 AM" },
  { text: "Goodbye! Have a great day!", sender: "bot", time: "09:10 AM" }
];

export default messageChats;