const messageChats = [
  // Yesterday's Messages
  {
    text: "Hey! How's it going?",
    sender: "user",
    messageStatus: "read",
    time: "10:15 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Hey! I'm good. How about you?",
    sender: "bot",
    time: "10:16 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "I'm doing great! Just working on a project.",
    sender: "user",
    messageStatus: "read",
    time: "10:18 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Nice! What's the project about?",
    sender: "bot",
    time: "10:19 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Hey! How's it going?",
    sender: "user",
    messageStatus: "read",
    time: "10:15 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Hey! I'm good. How about you?",
    sender: "bot",
    time: "10:16 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "I'm doing great! Just working on a project.",
    sender: "user",
    messageStatus: "read",
    time: "10:18 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Nice! What's the project about?",
    sender: "bot",
    time: "10:19 AM",
    timestamp: "2025-02-23",
  },

  {
    text: "Hey! How's it going?",
    sender: "user",
    messageStatus: "read",
    time: "10:15 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Hey! I'm good. How about you?",
    sender: "bot",
    time: "10:16 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "I'm doing great! Just working on a project.",
    sender: "user",
    messageStatus: "read",
    time: "10:18 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Nice! What's the project about?",
    sender: "bot",
    time: "10:19 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Hey! How's it going?",
    sender: "user",
    messageStatus: "read",
    time: "10:15 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Hey! I'm good. How about you?",
    sender: "bot",
    time: "10:16 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "I'm doing great! Just working on a project.",
    sender: "user",
    messageStatus: "read",
    time: "10:18 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Nice! What's the project about?",
    sender: "bot",
    time: "10:19 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Hey! How's it going?",
    sender: "user",
    messageStatus: "read",
    time: "10:15 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Hey! I'm good. How about you?",
    sender: "bot",
    time: "10:16 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "I'm doing great! Just working on a project.",
    sender: "user",
    messageStatus: "read",
    time: "10:18 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Nice! What's the project about?",
    sender: "bot",
    time: "10:19 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "It's a WhatsApp UI clone in React Native!",
    sender: "user",
    messageStatus: "read",
    time: "10:20 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "That sounds interesting. Need any help?",
    sender: "bot",
    time: "10:21 AM",
    timestamp: "2025-02-23",
  },
  {
    text: "Not right now, but I'll let you know!",
    sender: "user",
    messageStatus: "read",
    time: "10:22 AM",
    timestamp: "2025-02-23",
  },

  // Today's Messages
  {
    text: "Good morning! What’s the plan for today?",
    sender: "bot",
    time: "08:00 AM",
    timestamp: "2025-02-24",
  },
  {
    text: "Hey, good morning! Just some coding and maybe a coffee break!",
    sender: "user",
    messageStatus: "read",
    time: "08:02 AM",
    timestamp: "2025-02-24",
  },
  {
    text: "Sounds like a productive day!",
    sender: "bot",
    time: "08:05 AM",
    timestamp: "2025-02-24",
  },
  {
    text: "Yeah, trying to stay consistent!",
    sender: "user",
    messageStatus: "read",
    time: "08:10 AM",
    timestamp: "2025-02-24",
  },
  {
    text: "That’s the spirit! Keep going!",
    sender: "bot",
    time: "08:12 AM",
    timestamp: "2025-02-24",
  },
];

export default messageChats;
